name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: platformio run
        working-directory: .

      - name: Create a Git Tag
        run: |
          TAG="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          git tag $TAG
          git push origin $TAG
